Feature/styling components
codingAngarita/react-calculator pull request #3
Opened 2020-08-14 20:30 UTC by codingAngarita

# Hi :rocket: 

On this feature I introduced styling for the calculator.

### Introduced changes:
* Added `node-sass` package.
* Added a `color` prop to the Button component.
* Added a `wide` prop to the Button component.
* Added variables file with the colors used.
* Added styling for every component.

@codingAngarita :wave:

2020-08-15 17:03 UTC, shshamim63 requested changes
## :recycle: Changes Required :recycle: 
___
Hi @codingAngarita :wave: 
Awesome job, the design actually looks way closer to the given template. Just a simple issue blocked me from approving this milestone. Please resolve it and send another review request.
___
### :spades: Mandatory Changes :spades: 
___
- You need to pass the wide prop in the Button '0' component. Cause without that it is not going to apply the width that it should get. Currently, it looks like this.
![image](https://user-images.githubusercontent.com/38625956/90317448-7b284780-df4b-11ea-907d-08009a68471f.png)
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-08-15 17:03 UTC, shshamim63 commented on src/components/ButtonPanel.js
> +        <Button buttonName="0" />
You need the pass the prop wide with Button '0' component.

2020-08-15 18:25 UTC, codingAngarita commented
# Hi! :robot: 

### New changes:
* Added the wide prop for button `0` **_oops!_**

@codingAngarita :wave:

2020-08-16 14:40 UTC, suretrust approved these changes
Hi @codingAngarita, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

_Good luck with your future milestones and happy coding!_ 🎉

2020-08-17 04:34 UTC, merged