Feature/adding calculator logic
codingAngarita/react-calculator pull request #4
Opened 2020-08-17 17:01 UTC by codingAngarita

## Hi! :robot: 

### Introduced changes:

* Added calculate module
* Added operate module

@codingAngarita :wave:

2020-08-17 20:16 UTC, suretrust requested changes
Hi @codingAngarita, 👋 

### Great job thus far! 🙌 Please see my comments. 👇 

- [ ] `calculate.js` should be imported in the `App` component.

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

2020-08-17 20:16 UTC, suretrust commented on src/logic/operate.js
> +  };
We should also take care of `%` in this file. 
* [ ] `operate` switches `operation` and uses `plus`, `minus`, `times`, `div` and `modifier` (turning the number into a percentage based number, `e.g. 95 % == .95`) functions ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone4/performOperate.png))

2020-08-17 22:15 UTC, codingAngarita commented on src/logic/calculate.js
> +  const modifiers = ['+/-', '%'];
Here I added `+/-` and `%` as modifiers

2020-08-17 22:16 UTC, codingAngarita commented on src/logic/calculate.js
> +    const makePercentage = number => operate(number, 100, '÷');
Here I used the operate module if the `buttonName` equals `%`.

2020-08-17 22:21 UTC, codingAngarita commented
# Hi!

I currently treat the `%` logic in the `calculate` module. I implemented it as a "modifier" just as the `+/-`.
On the comments I highlighted were I addressed the modifiers.

As I implemented it the `operate` module has a single responsibility, it just operates two number, I believe that  adding the modifiers logic would be a bad design design decision.

@codingAngarita :wave:

2020-08-18 13:27 UTC, suretrust approved these changes
Hi @codingAngarita, 👋 

### Even though this ☝️ is a requirement, I agree with your assessment/initiative. 🙌 Let's get this merged! 👍 

_Good luck with your future milestones and happy coding!_ 🎉

2020-08-18 13:39 UTC, merged